### ISSUE TITLE
Problem running the script

### ISSUE THREAD

**Issue by Arini11** [11Tuvork28/moodle_scrapping_discord_bot#1]
I'll go straight to the point. I've never used python before. When I'm trying to execute the python file, it says to me that get_link.py has an invalid syntax. I don't really know what's happenig. By the way, should I run it with python2 or 3?
If you're asking yourselve if I've installed all the dependencies. Yes, or that's what I think.
I'm sorry if I'm asking a stupid or very trivial question but I am completely new to Python.
![image](https://user-images.githubusercontent.com/57038668/106322265-e190f000-6275-11eb-97e4-72a077c760c1.png)

**Comment by AndromedaCLI** [comment]
This is python3 only and the error you're getting is caused by an error in the robobrowser package and apparantly I made it work on my pc. I will update the repo but this will programm will only work if your moodle site uses the standard design

**Comment by Arini11** [comment]
I belive it uses the standard design. By the way, I've solved it by adding this before the robobrowser import
`import werkzeug`
`werkzeug.cached_property = werkzeug.utils.cached_property`
![image](https://user-images.githubusercontent.com/57038668/106324501-88c35680-6279-11eb-9b99-9e543c25a646.png)
