### ISSUE TITLE
How to set the login credentials?

### ISSUE THREAD

**Issue by Arini11** [11Tuvork28/moodle_scrapping_discord_bot#2]
Now new errors come up, I keep without knowing very well what I'm doing, but could this be related to what you explained in the last ticket? Also, I see, at the last line, a "LoginFailure". Could this be happening because I haven't set the user nor password in any way? I mean, is the program supposed to ask you for your login credentials, or this was adjusted to your specific case, and so, I would have to change the code in order to adjust it to my case?
Sorry if I'm asking too much questions, but I'm trying to figure this out. This is the last ticket I write without knowing anything, I promise. Tomorrow I'll start learning python and the robobrowser web scrapper.
Thanks.
P.D Not the best ticket title i think :p

![image](https://user-images.githubusercontent.com/57038668/106325375-0176e280-627b-11eb-99bf-9b53f96d5c45.png)

**Comment by AndromedaCLI** [comment]
Well thats my fault lack of documentation. I
n get_link.py you need to set your username and password for your moodle site and at the bottom you need to replace the link with your the link to the moodle site. 
In main_bot.py you need to set your discord bot token. 
Thats it

**Comment by AndromedaCLI** [comment]
Feel the to open issues if you have any other questions or so. And you may have to edit the code to make it word with your site, you may also wanna set the discord channel to post to in the main_bot.py
